export const ADMISSION_CREATE_REQUEST = "ADMISSION_CREATE_REQUEST";
export const ADMISSION_CREATE_SUCCESS = "ADMISSION_CREATE_SUCCESS";
export const ADMISSION_CREATE_FAIL = "ADMISSION_CREATE_FAIL";

export const ADMISSION_LIST_REQUEST = "ADMISSION_LIST_REQUEST";
export const ADMISSION_LIST_SUCCESS = "ADMISSION_LIST_SUCCESS";
export const ADMISSION_LIST_FAIL = "ADMISSION_LIST_FAIL";