export const ATTENDACES_CREATE_REQUEST = "ATTENDACES_CREATE_REQUEST";
export const ATTENDACES_CREATE_SUCCESS = "ATTENDACES_CREATE_SUCCESS";
export const ATTENDACES_CREATE_FAIL = "ATTENDACES_CREATE_FAIL";

export const ATTENDACES_LIST_REQUEST = "ATTENDACES_LIST_REQUEST";
export const ATTENDACES_LIST_SUCCESS = "ATTENDACES_LIST_SUCCESS";
export const ATTENDACES_LIST_FAIL = "ATTENDACES_LIST_FAIL";

export const ATTENDACES_UPDATE_REQUEST = "ATTENDACES_UPDATE_REQUEST";
export const ATTENDACES_UPDATE_SUCCESS = "ATTENDACES_UPDATE_SUCCESS";
export const ATTENDACES_UPDATE_FAIL = "ATTENDACES_UPDATE_FAIL";

export const ATTENDACE_ADMIN_LIST_REQUEST = "ATTENDACE_ADMIN_lIST_REQUEST";
export const ATTENDACE_ADMIN_LIST_SUCCESS = "ATTENDACE_ADMIN_lIST_SUCCESS";
export const ATTENDACE_ADMIN_LIST_FAIL = "ATTENDACE_ADMIN_lIST_FAIL";
