export const ATTENDACES_CREATE_REQUEST = "ATTENDACES_CREATE_REQUEST";
export const ATTENDACES_CREATE_SUCCESS = "ATTENDACES_CREATE_SUCCESS";
export const ATTENDACES_CREATE_FAIL = "ATTENDACES_CREATE_FAIL";

export const ATTENDACES_LIST_REQUEST = "ATTENDACES_LIST_REQUEST";
export const ATTENDACES_LIST_SUCCESS = "ATTENDACES_LIST_SUCCESS";
export const ATTENDACES_LIST_FAIL = "ATTENDACES_LIST_FAIL"; 
