export const WALKIN_CREATE_REQUEST = "WALKIN_CREATE_REQUEST";
export const WALKIN_CREATE_SUCCESS = "WALKIN_CREATE_SUCCESS";
export const WALKIN_CREATE_FAIL = "WALKIN_CREATE_FAIL";

export const WALKIN_LIST_REQUEST = "WALKIN_LIST_REQUEST";
export const WALKIN_LIST_SUCCESS = "WALKIN_LIST_SUCCESS";
export const WALKIN_LIST_FAIL = "WALKIN_LIST_FAIL";